name = "CompositeStructs"
uuid = "534720e6-2374-40c5-8712-bf9a2f1643c6"
authors = ["Marius Millea <mariusmillea@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
